# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobile-ios-sdk' do
  # Comment the next line if you don't want to use dynamic frameworks
   use_frameworks!
  #use_frameworks! :linkage => :static
#
#    pod ‘gRPC-Swift’, ‘~> 1.8.0’
#    pod ‘gRPC-Swift-Plugins’
## pod 'SwiftProtobuf', '~> 1.0'
#    pod ’SwiftLog’, ’~> 1.0.0’

  target 'mobile-ios-sdkTests' do
    # Pods for testing
  end
  
  post_install do |installer|
      installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
              end
          end
      end
#      installer.pods_project.targets.each do |target|
#         target.build_configurations.each do |config|
#           config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
#         end
#       end
#      installer.pods_project.targets.each do |target|
#          puts "#{target.name}" if target.name == "gRPC-Swift" || target.name == "SwiftNIO" || target.name == "SwiftNIOConcurrencyHelpers" || target.name == "SwiftNIOExtras" || target.name == "SwiftNIOFoundationCompat" || target.name == "SwiftNIOHPACK" || target.name == "SwiftNIOHTTP1" || target.name == "SwiftNIOHTTP2" || target.name == "SwiftNIOSSL" || target.name == "SwiftNIOTLS" || target.name == "SwiftNIOTransportServices"
#          target.build_configurations.each do |config|
#              config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
#          end
#      end
  end
#  post_install do |installer|
#      installer.pods_project.targets.each do |target|
#          puts "#{target.name}" if target.name == "gRPC-Swift" || target.name == "SwiftNIO" || target.name == "SwiftNIOConcurrencyHelpers" || target.name == "SwiftNIOExtras" || target.name == "SwiftNIOFoundationCompat" || target.name == "SwiftNIOHPACK" || target.name == "SwiftNIOHTTP1" || target.name == "SwiftNIOHTTP2" || target.name == "SwiftNIOSSL" || target.name == "SwiftNIOTLS" || target.name == "SwiftNIOTransportServices"
#          target.build_configurations.each do |config|
#              config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
#          end
#      end
#  end

end
